
service: roadmap-github-webhook

provider:
  name: aws
  runtime: nodejs4.3
  region: ${file(./config.prod.json):region}
  environment:
    GITHUB_WEBHOOK_SECRET: ${file(./config.prod.json):githubSecret}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  githubWebhookListener:
    handler: handler.githubWebhookListener
    events:
      - http:
          path: webhook
          method: post
          integration: lambda
          cors: true
  getAll:
    handler: handler.getItems
    events:
      - http:
          path: issues
          method: get
          integration: lambda
          cors: true
  getRecentlyCompleted:
    handler: handler.getCompletedItems
    events:
      - http:
          path: completed
          method: get
          integration: lambda
          cors: true

resources:
  Resources:
    statusBoardOpenIssues:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: status_board_open_issues
        AttributeDefinitions:
          - AttributeName: number
            AttributeType: N
        KeySchema:
          - AttributeName: number
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    statusBoardClosedIssues:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: status_board_closed_issues
        AttributeDefinitions:
          - AttributeName: number
            AttributeType: N
        KeySchema:
          - AttributeName: number
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
